import type { Metadata } from "next";
import React from "react";
import "@app/styles/globals.css";
import { Navbar } from "@/app/pages/home/navbar";

export const metadata: Metadata = {
  title: "OBAC.ac.th",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="mt-32">
         {children} 
        </div>
        
      </body>
    </html>
  );
}
